Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,7 +30,9 @@ jobs:
       run: python main.py
 
     - name: Run medium.py
-      run: python medium.py
+      run: |
+           python medium.py || echo "Medium script failed"
+
 
     - name: Commit changes
       run: |
@@ -38,5 +40,4 @@ jobs:
         git config --global user.email 'github-actions@github.com'
         git add .
         git commit -m "Update GitHub stats and Medium feed"
-        git push origin main
-      continue-on-error: true
+        git push origin main || echo "Error"
